### ISSUE TITLE
Automatic Install - Config File (chg-010-004)

### ISSUE THREAD

**Issue by LittleClumsy** [LittleClumsy/ToDo_CLI#7]
### Narrative

As a user of ToDo CLI,
I want the config file to be automatically installed
so that I do not have to worry about any setup.

### Scenario 1

Given I have not run ToDo CLI on my device before,
When I run it for the first time,
Then it should automatically install the config file in a hidden directory.

### Scenario 2

Given I have run ToDo CLI on my device before 
and the files have not been deleted
When I run it again,
Then it should skip installing the config file.

### Acceptance Criteria

- [x] Cross Platform (Windows and Ubuntu).
- [x] Automatically creates directory, if it does not exist.
- [x] Automatically creates config.json file, if it does not exist.
- [x] Automatically populate config.json file with data, it there is none.

**Comment by LittleClumsy** [comment]
1. Be cross platform - work on Windows and Ubuntu.
2. mkdir .todo (Make hidden folder)
3. touch .todo/config.json (Makes file in a folder)
4.  Search ExpandUser
5. Empty data_storage string in json file

**Comment by Evanlab02** [comment]
@LittleClumsy you can do this ticket on branch `chg-010-004`, in future I will add branch names for specific tickets to the top of the description of the ticket.

**Comment by Evanlab02** [comment]
![Image](https://user-images.githubusercontent.com/36800222/226440793-21dbdd2a-63a6-415b-84ed-792ff6e15671.png)

**Comment by Evanlab02** [comment]
![Image](https://user-images.githubusercontent.com/36800222/226440863-46807de3-b413-4339-bdee-e63fb2d1c067.png)

**Comment by Evanlab02** [comment]
Home Directory - https://stackoverflow.com/a/4028943
Creating Directories - https://docs.python.org/3.10/library/os.html?highlight=mkdir#os.mkdir
Checking if directories exist - https://docs.python.org/3.10/library/os.path.html?highlight=os%20path%20exists#os.path.exists
JSON - https://docs.python.org/3.10/library/json.html
Creating/Writing Files - https://www.w3schools.com/python/python_file_write.asp
